# This is a basic workflow to help you get started with Actions
name: publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
    # Push events on staging branch
    branches: [ staging ]
      # OR
      # - staging
    # Push events to v1.0, v1.1, and v1.9 tags
    tags:
      - v1.*
  # pull_request:
    # branches: [ staging ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Extract branch name
        if: startsWith(github.ref, 'refs/heads/')
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse HEAD)"
        id: extract_branch

        # https://github.community/t/how-to-get-just-the-tag-name/16241
        # SOURCE_NAME : The heads or the tags
        # SOURCE_BRANCH : The [head] or empty
        # SOURCE_TAG : The [tag] or empty
        # echo "::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}"
        # echo "::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}"
        # echo "::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}"
      - name: Extract tag name
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_tag

      # Runs a single command using the runners shell
      - name: Install Packages
        run: npm install

      # Runs a set of commands using the runners shell
      - name: Build Packages
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOYMENT_TOKEN }}
          publish_dir: ./dist
